### ISSUE TITLE
[feature suggestion] Make spoon available via Homebrew for easier installation

### ISSUE THREAD

**Issue by scorchio** [endreymarcell/spoon#1]
As explained in Homebrew's ["How to Create and Maintain a Tap"](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md).

**Comment by endreymarcell** [comment]
Done with https://github.com/endreymarcell/spoon/commit/083137bd9d9de1cc8ffc486004756219283535d1

**Comment by scorchio** [comment]
Great, thanks! :)
