### ISSUE TITLE
Reload cache on SSH failure

### ISSUE THREAD

**Issue by banrobert** [endreymarcell/spoon#22]
### Problem
When `spoon` uses its cache to show the results for a given search query, the cache can be outdated and one could potentially try to SSH into a terminated node. When that happens, the SSH connection fails and `spoon` exits too.

Today to overcome this one must re-run the search query and use the `-r` flag to reload the whole cache.

### Proposed solution
When running `spoon` with a search query, after SSH-ing into one of the instances that were in the search results if the SSH connection fails for some reason then make `spoon` reload the cache for the given search query and display the search results for the query one more time (instead of exiting right away).

**Comment by endreymarcell** [comment]
Added in https://github.com/endreymarcell/spoon/commit/7993a2afa8edc00edf36a2171807965ff7af86cb, keeping the issue open until tests are also added.

**Comment by endreymarcell** [comment]
Tests added in https://github.com/endreymarcell/spoon/commit/2b9bfd671129034c01a81b6bf2a3d11716a88c51
